version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - env/mongo.env
    volumes:
      - "mongo:/data/db"
    ports:
      - 27017:27017
    networks:
      - wedding-network

  wedding-app:
    image: wedding-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wedding-app
    env_file:
      - env/app.env
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - wedding-network
    depends_on:
      - mongo

volumes:
  mongo:

networks:
  wedding-network:
    driver: bridge
