FROM golang:1.17.6-alpine as build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN apk update && \
    apk add --no-cache curl==7.80.0-r0 && \
    curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh && \
    chmod +x install.sh && \
    sh install.sh && \
    cp ./bin/air /bin/air

CMD air
