version: "3.9"
services:
  wedding-app:
    image: starlightromero/wedding-app
    container_name: wedding-app
    env_file:
      - env/app.env
    ports:
      - 8080:8080
    networks:
      - wedding-network

networks:
  wedding-network:
    driver: bridge
